-- NutmegPlay hosted Supabase bootstrap
-- Run this on a new or empty hosted Supabase project.
-- If this project already contains live app tables/data, stop and review before running.

create extension if not exists pgcrypto;

create table if not exists public.accounts (
    id bigint generated by default as identity primary key,
    uid uuid not null unique,
    email text not null unique,
    fname text not null,
    lname text,
    username text,
    country text,
    position text,
    image_url text,
    club_assign text,
    role text not null default 'player',
    login_type text,
    level integer not null default 1,
    created_at timestamptz not null default now(),
    constraint accounts_role_check check (role in ('player', 'instructor', 'admin'))
);

create table if not exists public.player_progress (
    id uuid primary key default gen_random_uuid(),
    user_id uuid not null unique,
    ovr integer not null default 50 check (ovr between 1 and 99),
    current_xp integer not null default 0 check (current_xp >= 0),
    pace integer not null default 50,
    shooting integer not null default 50,
    passing integer not null default 50,
    dribbling integer not null default 50,
    defending integer not null default 50,
    physical integer not null default 50,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.clubs (
    id bigint generated by default as identity primary key,
    name text not null unique,
    logo text,
    owner uuid,
    level integer not null default 1,
    ranking integer not null default 0,
    number_player integer not null default 1,
    team_active boolean not null default true,
    field_layout text,
    team_bench text,
    players jsonb,
    created_at timestamptz not null default now()
);

create table if not exists public.invites (
    id bigint generated by default as identity primary key,
    club jsonb,
    sent_by uuid,
    sent_to uuid not null,
    status text not null default 'pending',
    payment text,
    created_at timestamptz not null default now()
);

create table if not exists public.matchs (
    id bigint generated by default as identity primary key,
    challanger text not null,
    opponent text,
    challange_status text not null default 'pending',
    location text,
    loc_codrinates text,
    date date not null default current_date,
    time time not null default current_time,
    match_status text not null default 'pending',
    challenger_id uuid,
    opponent_id uuid,
    result text,
    score_home integer,
    score_away integer,
    score_challanger integer,
    score_opponent integer,
    video_url text,
    video_status text,
    created_at timestamptz not null default now()
);

create table if not exists public.match_stats (
    id uuid primary key default gen_random_uuid(),
    match_id bigint not null references public.matchs(id) on delete cascade,
    user_id uuid not null,
    goals integer not null default 0,
    assists integer not null default 0,
    distance_meters integer not null default 0,
    distance numeric(8,2) not null default 0,
    sprints integer not null default 0,
    successful_passes integer not null default 0,
    passes_attempted integer not null default 0,
    passes integer not null default 0,
    successful_dribbles integer not null default 0,
    dribbles_attempted integer not null default 0,
    dribbles integer not null default 0,
    interceptions integer not null default 0,
    duels_won integer not null default 0,
    duels integer not null default 0,
    minutes_played integer not null default 0,
    result text,
    clean_sheet boolean not null default false,
    match_winning_goal boolean not null default false,
    team_win_streak integer not null default 0,
    created_at timestamptz not null default now(),
    constraint match_stats_match_user_key unique (match_id, user_id),
    constraint match_stats_result_check check (result in ('win', 'draw', 'loss') or result is null)
);

create table if not exists public.announcement (
    id bigint generated by default as identity primary key,
    title text,
    message text,
    club text,
    user_id uuid,
    location text,
    date text,
    time text,
    response text,
    requests jsonb not null default '[]'::jsonb,
    created_at timestamptz not null default now()
);

create table if not exists public.xp_history (
    id uuid primary key default gen_random_uuid(),
    user_id uuid not null,
    match_id bigint references public.matchs(id) on delete set null,
    xp_gained integer not null default 0 check (xp_gained >= 0),
    reason text,
    created_at timestamptz not null default now()
);

create table if not exists public.notifications (
    id bigint generated by default as identity primary key,
    user_id uuid not null,
    type text not null default 'general',
    title text not null,
    message text,
    icon text default 'notifications',
    link text,
    is_read boolean not null default false,
    created_at timestamptz not null default now()
);

create table if not exists public.challenge_templates (
    id bigint generated by default as identity primary key,
    title text not null,
    description text,
    type text not null default 'daily',
    xp_reward integer not null default 50,
    target_value integer not null default 1,
    metric text not null default 'goals',
    start_date date,
    end_date date,
    is_active boolean not null default true,
    created_by uuid,
    created_at timestamptz not null default now(),
    constraint challenge_templates_type_check check (type in ('daily', 'weekly', 'monthly'))
);

create table if not exists public.match_video_analysis (
    id uuid primary key default gen_random_uuid(),
    match_id bigint not null unique references public.matchs(id) on delete cascade,
    video_url text,
    video_source_type text not null default 'local_upload',
    processing_status text not null default 'pending',
    ai_output jsonb,
    team_stats jsonb,
    player_stats jsonb,
    normalized_stats jsonb,
    error_message text,
    uploaded_by uuid,
    queued_at timestamptz not null default now(),
    processed_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.match_jersey_slots (
    id bigint generated by default as identity primary key,
    match_id bigint not null references public.matchs(id) on delete cascade,
    team_color text not null,
    jersey_number integer not null,
    player_uid uuid,
    player_name text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint match_jersey_slots_team_number_check check (
        (team_color = 'blue' and jersey_number between 1 and 5)
        or
        (team_color = 'red' and jersey_number between 6 and 10)
    ),
    constraint match_jersey_slots_match_number_key unique (match_id, jersey_number)
);

create table if not exists public.match_jersey_stats (
    id bigint generated by default as identity primary key,
    match_id bigint not null references public.matchs(id) on delete cascade,
    team_color text not null,
    jersey_number integer not null,
    player_uid uuid,
    player_name text,
    goals integer not null default 0,
    assists integer not null default 0,
    distance_meters integer not null default 0,
    sprints integer not null default 0,
    successful_passes integer not null default 0,
    passes_attempted integer not null default 0,
    successful_dribbles integer not null default 0,
    dribbles_attempted integer not null default 0,
    interceptions integer not null default 0,
    duels_won integer not null default 0,
    shots integer not null default 0,
    top_speed_kmh numeric(8,2) not null default 0,
    minutes_played integer not null default 0,
    clean_sheet boolean not null default false,
    match_winning_goal boolean not null default false,
    team_win_streak integer not null default 0,
    result text,
    raw_player_key text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint match_jersey_stats_team_number_check check (
        (team_color = 'blue' and jersey_number between 1 and 5)
        or
        (team_color = 'red' and jersey_number between 6 and 10)
    ),
    constraint match_jersey_stats_match_number_key unique (match_id, jersey_number),
    constraint match_jersey_stats_result_check check (result in ('win', 'draw', 'loss') or result is null)
);

create index if not exists idx_matchs_created_at on public.matchs(created_at desc);
create index if not exists idx_match_stats_user_id on public.match_stats(user_id);
create index if not exists idx_match_stats_match_id on public.match_stats(match_id);
create index if not exists idx_xp_history_user_id on public.xp_history(user_id);
create index if not exists idx_notifications_user_id on public.notifications(user_id);
create index if not exists idx_notifications_unread on public.notifications(user_id, is_read) where is_read = false;
create index if not exists idx_match_video_analysis_status on public.match_video_analysis(processing_status);
create index if not exists idx_match_jersey_slots_match_id on public.match_jersey_slots(match_id);
create index if not exists idx_match_jersey_stats_match_id on public.match_jersey_stats(match_id);

grant usage on schema public to anon, authenticated, service_role;

revoke all privileges on all tables in schema public from anon, authenticated;
revoke all privileges on all sequences in schema public from anon, authenticated;

grant all privileges on all tables in schema public to service_role;
grant all privileges on all sequences in schema public to service_role;

alter default privileges in schema public revoke all on tables from anon, authenticated;
alter default privileges in schema public revoke all on sequences from anon, authenticated;
alter default privileges in schema public grant all on tables to service_role;
alter default privileges in schema public grant all on sequences to service_role;
