-- Notifications table for in-app notifications
create table if not exists public.notifications (
    id bigint generated by default as identity primary key,
    user_id uuid not null,
    type text not null default 'general',
    title text not null,
    message text,
    icon text default 'notifications',
    link text,
    is_read boolean not null default false,
    created_at timestamptz not null default now()
);

create index if not exists idx_notifications_user_id on public.notifications(user_id);
create index if not exists idx_notifications_unread on public.notifications(user_id, is_read) where is_read = false;

-- Challenge templates created by admins/instructors
create table if not exists public.challenge_templates (
    id bigint generated by default as identity primary key,
    title text not null,
    description text,
    type text not null default 'daily',          -- daily, weekly, monthly
    xp_reward integer not null default 50,
    target_value integer not null default 1,      -- e.g. score 3 goals
    metric text not null default 'goals',         -- goals, assists, wins, matches, distance
    start_date date,
    end_date date,
    is_active boolean not null default true,
    created_by uuid,
    created_at timestamptz not null default now()
);

-- Grant access
revoke all privileges on public.notifications from anon, authenticated;
revoke all privileges on public.challenge_templates from anon, authenticated;
grant all privileges on public.notifications to service_role;
grant all privileges on public.challenge_templates to service_role;
grant usage, select on all sequences in schema public to service_role;
