create table if not exists public.match_jersey_slots (
    id bigint generated by default as identity primary key,
    match_id bigint not null references public.matchs(id) on delete cascade,
    team_color text not null,
    jersey_number integer not null,
    player_uid uuid,
    player_name text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint match_jersey_slots_team_number_check check (
        (team_color = 'blue' and jersey_number between 1 and 5)
        or
        (team_color = 'red' and jersey_number between 6 and 10)
    ),
    constraint match_jersey_slots_match_number_key unique (match_id, jersey_number)
);

create table if not exists public.match_jersey_stats (
    id bigint generated by default as identity primary key,
    match_id bigint not null references public.matchs(id) on delete cascade,
    team_color text not null,
    jersey_number integer not null,
    player_uid uuid,
    player_name text,
    goals integer not null default 0,
    assists integer not null default 0,
    distance_meters integer not null default 0,
    sprints integer not null default 0,
    successful_passes integer not null default 0,
    passes_attempted integer not null default 0,
    successful_dribbles integer not null default 0,
    dribbles_attempted integer not null default 0,
    interceptions integer not null default 0,
    duels_won integer not null default 0,
    shots integer not null default 0,
    top_speed_kmh numeric(8,2) not null default 0,
    minutes_played integer not null default 0,
    clean_sheet boolean not null default false,
    match_winning_goal boolean not null default false,
    team_win_streak integer not null default 0,
    result text,
    raw_player_key text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint match_jersey_stats_team_number_check check (
        (team_color = 'blue' and jersey_number between 1 and 5)
        or
        (team_color = 'red' and jersey_number between 6 and 10)
    ),
    constraint match_jersey_stats_match_number_key unique (match_id, jersey_number)
);

create index if not exists idx_match_jersey_slots_match_id on public.match_jersey_slots(match_id);
create index if not exists idx_match_jersey_stats_match_id on public.match_jersey_stats(match_id);

revoke all privileges on public.match_jersey_slots from anon, authenticated;
revoke all privileges on public.match_jersey_stats from anon, authenticated;
grant all privileges on public.match_jersey_slots to service_role;
grant all privileges on public.match_jersey_stats to service_role;
