-- NutmegPlay production compatibility migration
--
-- Purpose:
-- - Safely align an older/live production schema with the current PHP app
-- - Avoid destructive casts that could orphan existing data
-- - Preserve legacy UUID match references in backup columns for manual review
--
-- Important:
-- - This is intended for an existing production database.
-- - Do NOT run database/init/00-hosted-bootstrap.sql on a live production schema.
-- - Review the notices after execution, especially around legacy UUID match ids.

create extension if not exists pgcrypto;

-- ---------------------------------------------------------------------------
-- 1. Missing supporting tables used by the current app
-- ---------------------------------------------------------------------------

create table if not exists public.notifications (
    id bigint generated by default as identity primary key,
    user_id uuid not null,
    type text not null default 'general',
    title text not null,
    message text,
    icon text default 'notifications',
    link text,
    is_read boolean not null default false,
    created_at timestamptz not null default now()
);

create table if not exists public.challenge_templates (
    id bigint generated by default as identity primary key,
    title text not null,
    description text,
    type text not null default 'daily',
    xp_reward integer not null default 50,
    target_value integer not null default 1,
    metric text not null default 'goals',
    start_date date,
    end_date date,
    is_active boolean not null default true,
    created_by uuid,
    created_at timestamptz not null default now(),
    constraint challenge_templates_type_check check (type in ('daily', 'weekly', 'monthly'))
);

create table if not exists public.match_video_analysis (
    id uuid primary key default gen_random_uuid(),
    match_id bigint not null unique references public.matchs(id) on delete cascade,
    video_url text,
    video_source_type text not null default 'local_upload',
    processing_status text not null default 'pending',
    ai_output jsonb,
    team_stats jsonb,
    player_stats jsonb,
    normalized_stats jsonb,
    error_message text,
    progress_stage text,
    progress_percent integer not null default 0,
    progress_message text,
    uploaded_by uuid,
    queued_at timestamptz not null default now(),
    processed_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.match_jersey_slots (
    id bigint generated by default as identity primary key,
    match_id bigint not null references public.matchs(id) on delete cascade,
    team_color text not null,
    jersey_number integer not null,
    player_uid uuid,
    player_name text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint match_jersey_slots_team_number_check check (
        (team_color = 'blue' and jersey_number between 1 and 5)
        or
        (team_color = 'red' and jersey_number between 6 and 10)
    ),
    constraint match_jersey_slots_match_number_key unique (match_id, jersey_number)
);

create table if not exists public.match_jersey_stats (
    id bigint generated by default as identity primary key,
    match_id bigint not null references public.matchs(id) on delete cascade,
    team_color text not null,
    jersey_number integer not null,
    player_uid uuid,
    player_name text,
    goals integer not null default 0,
    assists integer not null default 0,
    distance_meters integer not null default 0,
    sprints integer not null default 0,
    successful_passes integer not null default 0,
    passes_attempted integer not null default 0,
    successful_dribbles integer not null default 0,
    dribbles_attempted integer not null default 0,
    interceptions integer not null default 0,
    duels_won integer not null default 0,
    shots integer not null default 0,
    top_speed_kmh numeric(8,2) not null default 0,
    minutes_played integer not null default 0,
    clean_sheet boolean not null default false,
    match_winning_goal boolean not null default false,
    team_win_streak integer not null default 0,
    result text,
    raw_player_key text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint match_jersey_stats_team_number_check check (
        (team_color = 'blue' and jersey_number between 1 and 5)
        or
        (team_color = 'red' and jersey_number between 6 and 10)
    ),
    constraint match_jersey_stats_match_number_key unique (match_id, jersey_number),
    constraint match_jersey_stats_result_check check (result in ('win', 'draw', 'loss') or result is null)
);

-- ---------------------------------------------------------------------------
-- 2. Safe additive compatibility columns
-- ---------------------------------------------------------------------------

alter table public.announcement
    add column if not exists title text;

alter table public.accounts
    add column if not exists role text;

alter table public.matchs
    add column if not exists score_home integer,
    add column if not exists score_away integer,
    add column if not exists score_challanger integer,
    add column if not exists score_opponent integer;

update public.accounts
set role = case
    when lower(coalesce(role, '')) in ('player', 'instructor', 'admin') then lower(role)
    when lower(coalesce(login_type, '')) in ('player', 'instructor', 'admin') then lower(login_type)
    else 'player'
end
where role is null
   or lower(coalesce(role, '')) not in ('player', 'instructor', 'admin');

do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where conname = 'accounts_role_check'
          and conrelid = 'public.accounts'::regclass
    ) then
        alter table public.accounts
            add constraint accounts_role_check
            check (role in ('player', 'instructor', 'admin') or role is null);
    end if;
end $$;

-- ---------------------------------------------------------------------------
-- 3. Convert match_stats.match_id to bigint safely
--    Preserve any legacy values in legacy_match_id_uuid
-- ---------------------------------------------------------------------------

do $$
declare
    current_type text;
begin
    select pg_catalog.format_type(a.atttypid, a.atttypmod)
      into current_type
    from pg_attribute a
    join pg_class c on c.oid = a.attrelid
    join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'public'
      and c.relname = 'match_stats'
      and a.attname = 'match_id'
      and not a.attisdropped;

    if current_type is null then
        raise notice 'match_stats.match_id was not found.';
    elsif current_type <> 'bigint' then
        if not exists (
            select 1
            from information_schema.columns
            where table_schema = 'public'
              and table_name = 'match_stats'
              and column_name = 'legacy_match_id_uuid'
        ) then
            alter table public.match_stats rename column match_id to legacy_match_id_uuid;
            alter table public.match_stats add column match_id bigint;
            alter table public.match_stats alter column legacy_match_id_uuid drop not null;

            update public.match_stats
            set match_id = case
                when trim(legacy_match_id_uuid::text, '"') ~ '^[0-9]+$'
                    then trim(legacy_match_id_uuid::text, '"')::bigint
                else null
            end;

            raise notice 'match_stats.match_id migrated to bigint. Legacy values preserved in legacy_match_id_uuid.';
        end if;
    end if;
end $$;

do $$
begin
    if exists (
        select 1
        from information_schema.columns
        where table_schema = 'public'
          and table_name = 'match_stats'
          and column_name = 'legacy_match_id_uuid'
          and is_nullable = 'NO'
    ) then
        alter table public.match_stats alter column legacy_match_id_uuid drop not null;
    end if;
end $$;

alter table public.match_stats
    add column if not exists distance numeric(8,2) not null default 0,
    add column if not exists passes integer not null default 0,
    add column if not exists dribbles integer not null default 0,
    add column if not exists duels integer not null default 0;

do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where conname = 'match_stats_match_id_fkey'
          and conrelid = 'public.match_stats'::regclass
    ) then
        alter table public.match_stats
            add constraint match_stats_match_id_fkey
            foreign key (match_id) references public.matchs(id) on delete cascade;
    end if;
exception
    when duplicate_object then null;
end $$;

do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where conname = 'match_stats_match_user_key'
          and conrelid = 'public.match_stats'::regclass
    ) then
        if not exists (
            select 1
            from public.match_stats
            where match_id is not null
            group by match_id, user_id
            having count(*) > 1
        ) then
            alter table public.match_stats
                add constraint match_stats_match_user_key unique (match_id, user_id);
        else
            raise notice 'Skipped match_stats_match_user_key because duplicate (match_id, user_id) rows already exist.';
        end if;
    end if;
end $$;

do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where conname = 'match_stats_result_check'
          and conrelid = 'public.match_stats'::regclass
    ) then
        alter table public.match_stats
            add constraint match_stats_result_check
            check (result in ('win', 'draw', 'loss') or result is null);
    end if;
end $$;

-- ---------------------------------------------------------------------------
-- 4. Convert xp_history.match_id to bigint safely
--    Preserve any legacy values in legacy_match_id_uuid
-- ---------------------------------------------------------------------------

do $$
declare
    current_type text;
begin
    select pg_catalog.format_type(a.atttypid, a.atttypmod)
      into current_type
    from pg_attribute a
    join pg_class c on c.oid = a.attrelid
    join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'public'
      and c.relname = 'xp_history'
      and a.attname = 'match_id'
      and not a.attisdropped;

    if current_type is null then
        raise notice 'xp_history.match_id was not found.';
    elsif current_type <> 'bigint' then
        if not exists (
            select 1
            from information_schema.columns
            where table_schema = 'public'
              and table_name = 'xp_history'
              and column_name = 'legacy_match_id_uuid'
        ) then
            alter table public.xp_history rename column match_id to legacy_match_id_uuid;
            alter table public.xp_history add column match_id bigint;
            alter table public.xp_history alter column legacy_match_id_uuid drop not null;

            update public.xp_history
            set match_id = case
                when trim(legacy_match_id_uuid::text, '"') ~ '^[0-9]+$'
                    then trim(legacy_match_id_uuid::text, '"')::bigint
                else null
            end;

            raise notice 'xp_history.match_id migrated to bigint. Legacy values preserved in legacy_match_id_uuid.';
        end if;
    end if;
end $$;

do $$
begin
    if exists (
        select 1
        from information_schema.columns
        where table_schema = 'public'
          and table_name = 'xp_history'
          and column_name = 'legacy_match_id_uuid'
          and is_nullable = 'NO'
    ) then
        alter table public.xp_history alter column legacy_match_id_uuid drop not null;
    end if;
end $$;

do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where conname = 'xp_history_match_id_fkey'
          and conrelid = 'public.xp_history'::regclass
    ) then
        alter table public.xp_history
            add constraint xp_history_match_id_fkey
            foreign key (match_id) references public.matchs(id) on delete set null;
    end if;
exception
    when duplicate_object then null;
end $$;

-- ---------------------------------------------------------------------------
-- 5. Helpful indexes expected by the current app
-- ---------------------------------------------------------------------------

create index if not exists idx_notifications_user_id
    on public.notifications(user_id);

create index if not exists idx_notifications_unread
    on public.notifications(user_id, is_read)
    where is_read = false;

create index if not exists idx_match_video_analysis_status
    on public.match_video_analysis(processing_status);

create index if not exists idx_match_jersey_slots_match_id
    on public.match_jersey_slots(match_id);

create index if not exists idx_match_jersey_stats_match_id
    on public.match_jersey_stats(match_id);

create index if not exists idx_match_stats_user_id
    on public.match_stats(user_id);

create index if not exists idx_match_stats_match_id
    on public.match_stats(match_id);

create index if not exists idx_xp_history_user_id
    on public.xp_history(user_id);

create index if not exists idx_xp_history_match_id
    on public.xp_history(match_id);

-- ---------------------------------------------------------------------------
-- 6. Privileges
-- ---------------------------------------------------------------------------

grant usage on schema public to anon, authenticated, service_role;

revoke all privileges on public.notifications from anon, authenticated;
revoke all privileges on public.challenge_templates from anon, authenticated;
revoke all privileges on public.match_video_analysis from anon, authenticated;
revoke all privileges on public.match_jersey_slots from anon, authenticated;
revoke all privileges on public.match_jersey_stats from anon, authenticated;

grant all privileges on public.notifications to service_role;
grant all privileges on public.challenge_templates to service_role;
grant all privileges on public.match_video_analysis to service_role;
grant all privileges on public.match_jersey_slots to service_role;
grant all privileges on public.match_jersey_stats to service_role;

grant usage, select on all sequences in schema public to service_role;
