<?php
/**
 * Create the notifications and challenge_templates tables on the remote Supabase.
 * Uses the Supabase REST API to perform raw SQL via the rpc endpoint.
 * If rpc is not available, falls back to creating a record to force schema cache.
 */
declare(strict_types=1);
require_once __DIR__ . '/../app/bootstrap.php';

use App\Core\SupabaseClient;

$sb = SupabaseClient::getInstance();

// Read Supabase config for direct HTTP calls
$config = require __DIR__ . '/../app/Config/supabase.php';
$url = rtrim($config['url'], '/');
$key = $config['service_role_key'] ?? $config['key'];

echo "Creating tables via Supabase SQL...\n";

$sql = <<<'SQL'
create table if not exists public.notifications (
    id bigint generated by default as identity primary key,
    user_id uuid not null,
    type text not null default 'general',
    title text not null,
    message text,
    icon text default 'notifications',
    link text,
    is_read boolean not null default false,
    created_at timestamptz not null default now()
);

create index if not exists idx_notifications_user_id on public.notifications(user_id);
create index if not exists idx_notifications_unread on public.notifications(user_id, is_read) where is_read = false;

create table if not exists public.challenge_templates (
    id bigint generated by default as identity primary key,
    title text not null,
    description text,
    type text not null default 'daily',
    xp_reward integer not null default 50,
    target_value integer not null default 1,
    metric text not null default 'goals',
    start_date date,
    end_date date,
    is_active boolean not null default true,
    created_by uuid,
    created_at timestamptz not null default now()
);

create table if not exists public.match_video_analysis (
    id uuid primary key default gen_random_uuid(),
    match_id bigint not null unique references public.matchs(id) on delete cascade,
    video_url text,
    video_source_type text not null default 'local_upload',
    processing_status text not null default 'pending',
    ai_output jsonb,
    team_stats jsonb,
    player_stats jsonb,
    normalized_stats jsonb,
    error_message text,
    uploaded_by uuid,
    queued_at timestamptz not null default now(),
    processed_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.match_jersey_slots (
    id bigint generated by default as identity primary key,
    match_id bigint not null references public.matchs(id) on delete cascade,
    team_color text not null,
    jersey_number integer not null,
    player_uid uuid,
    player_name text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint match_jersey_slots_team_number_check check (
        (team_color = 'blue' and jersey_number between 1 and 5)
        or
        (team_color = 'red' and jersey_number between 6 and 10)
    ),
    constraint match_jersey_slots_match_number_key unique (match_id, jersey_number)
);

create table if not exists public.match_jersey_stats (
    id bigint generated by default as identity primary key,
    match_id bigint not null references public.matchs(id) on delete cascade,
    team_color text not null,
    jersey_number integer not null,
    player_uid uuid,
    player_name text,
    goals integer not null default 0,
    assists integer not null default 0,
    distance_meters integer not null default 0,
    sprints integer not null default 0,
    successful_passes integer not null default 0,
    passes_attempted integer not null default 0,
    successful_dribbles integer not null default 0,
    dribbles_attempted integer not null default 0,
    interceptions integer not null default 0,
    duels_won integer not null default 0,
    shots integer not null default 0,
    top_speed_kmh numeric(8,2) not null default 0,
    minutes_played integer not null default 0,
    clean_sheet boolean not null default false,
    match_winning_goal boolean not null default false,
    team_win_streak integer not null default 0,
    result text,
    raw_player_key text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint match_jersey_stats_team_number_check check (
        (team_color = 'blue' and jersey_number between 1 and 5)
        or
        (team_color = 'red' and jersey_number between 6 and 10)
    ),
    constraint match_jersey_stats_match_number_key unique (match_id, jersey_number)
);

revoke all privileges on public.notifications from anon, authenticated;
revoke all privileges on public.challenge_templates from anon, authenticated;
revoke all privileges on public.match_video_analysis from anon, authenticated;
revoke all privileges on public.match_jersey_slots from anon, authenticated;
revoke all privileges on public.match_jersey_stats from anon, authenticated;
grant all privileges on public.notifications to service_role;
grant all privileges on public.challenge_templates to service_role;
grant all privileges on public.match_video_analysis to service_role;
grant all privileges on public.match_jersey_slots to service_role;
grant all privileges on public.match_jersey_stats to service_role;
grant usage, select on all sequences in schema public to service_role;
SQL;

// Try via the Supabase Management API (sql endpoint)
$sqlUrl = $url . '/rest/v1/rpc/exec_sql';
$ch = curl_init($sqlUrl);
curl_setopt_array($ch, [
    CURLOPT_RETURNTRANSFER => true,
    CURLOPT_POST => true,
    CURLOPT_HTTPHEADER => [
        'apikey: ' . $key,
        'Authorization: Bearer ' . $key,
        'Content-Type: application/json',
    ],
    CURLOPT_POSTFIELDS => json_encode(['query' => $sql]),
]);
$resp = curl_exec($ch);
$code = curl_getinfo($ch, CURLINFO_HTTP_CODE);
curl_close($ch);

if ($code >= 200 && $code < 300) {
    echo "Tables created via RPC.\n";
} else {
    echo "RPC not available (HTTP $code), trying direct POST method...\n";
    
    // Use the Supabase Dashboard SQL API or management API
    // Attempt via /rest/v1/ direct table creation by inserting a test row
    
    // notifications: attempt to insert & delete to auto-create
    $notifData = json_encode([
        'user_id' => '00000000-0000-0000-0000-000000000000',
        'type' => 'system',
        'title' => '__setup_test__',
        'message' => 'setup',
        'icon' => 'check',
        'is_read' => false,
    ]);
    
    echo "\nThe tables need to be created manually in the Supabase Dashboard.\n";
    echo "Go to: https://supabase.com/dashboard → SQL Editor → paste this:\n\n";
    echo $sql . "\n";
    echo "\n--- Or run this with the Supabase CLI: supabase db execute ---\n";

    // Alternative: try creating via query params approach
    // The PostgREST API itself cannot CREATE TABLE. We'll create a setup script.
    
    echo "\nAttempting alternative approach: creating tables via direct SQL endpoint...\n";
    
    // Try the /pg endpoint (some Supabase setups have this)
    $pgUrl = str_replace('/rest/v1', '', $url);
    $endpoints = [
        $pgUrl . '/rest/v1/rpc/exec_sql',
        $pgUrl . '/pg/query',
        $url . '/sql',
    ];
    
    $created = false;
    foreach ($endpoints as $endpoint) {
        $ch = curl_init($endpoint);
        curl_setopt_array($ch, [
            CURLOPT_RETURNTRANSFER => true,
            CURLOPT_POST => true,
            CURLOPT_HTTPHEADER => [
                'apikey: ' . $key,
                'Authorization: Bearer ' . $key,
                'Content-Type: application/json',
            ],
            CURLOPT_POSTFIELDS => json_encode(['query' => $sql]),
            CURLOPT_TIMEOUT => 10,
        ]);
        $resp = curl_exec($ch);
        $code = curl_getinfo($ch, CURLINFO_HTTP_CODE);
        curl_close($ch);
        
        if ($code >= 200 && $code < 300) {
            echo "Created successfully via $endpoint\n";
            $created = true;
            break;
        }
    }
    
    if (!$created) {
        echo "\nCould not auto-create tables. Please run the SQL manually.\n";
        echo "Attempting to use Supabase Management API...\n";
        
        // Get project ref from URL
        $projectRef = '';
        if (preg_match('/https:\/\/([a-z0-9]+)\.supabase\.co/', $url, $m)) {
            $projectRef = $m[1];
        }
        
        if ($projectRef) {
            $mgmtUrl = "https://api.supabase.com/v1/projects/{$projectRef}/database/query";
            $ch = curl_init($mgmtUrl);
            curl_setopt_array($ch, [
                CURLOPT_RETURNTRANSFER => true,
                CURLOPT_POST => true,
                CURLOPT_HTTPHEADER => [
                    'Authorization: Bearer ' . $key,
                    'Content-Type: application/json',
                ],
                CURLOPT_POSTFIELDS => json_encode(['query' => $sql]),
                CURLOPT_TIMEOUT => 15,
            ]);
            $resp = curl_exec($ch);
            $code = curl_getinfo($ch, CURLINFO_HTTP_CODE);
            curl_close($ch);
            
            if ($code >= 200 && $code < 300) {
                echo "Tables created via Management API!\n";
                $created = true;
            } else {
                echo "Management API returned HTTP $code\n";
            }
        }
    }
}

// Verify
echo "\nVerifying tables...\n";
$sb2 = SupabaseClient::getInstance();
$r1 = $sb2->from('notifications')->select('id')->limit(1)->execute();
$sb3 = SupabaseClient::getInstance();
$r2 = $sb3->from('challenge_templates')->select('id')->limit(1)->execute();
$sb4 = SupabaseClient::getInstance();
$r3 = $sb4->from('match_video_analysis')->select('id')->limit(1)->execute();
$sb5 = SupabaseClient::getInstance();
$r4 = $sb5->from('match_jersey_slots')->select('id')->limit(1)->execute();
$sb6 = SupabaseClient::getInstance();
$r5 = $sb6->from('match_jersey_stats')->select('id')->limit(1)->execute();

echo "notifications: " . ((!$r1 || !empty($r1['error'])) ? "MISSING" : "OK") . "\n";
echo "challenge_templates: " . ((!$r2 || !empty($r2['error'])) ? "MISSING" : "OK") . "\n";
echo "match_video_analysis: " . ((!$r3 || !empty($r3['error'])) ? "MISSING" : "OK") . "\n";
echo "match_jersey_slots: " . ((!$r4 || !empty($r4['error'])) ? "MISSING" : "OK") . "\n";
echo "match_jersey_stats: " . ((!$r5 || !empty($r5['error'])) ? "MISSING" : "OK") . "\n";

if ((!$r1 || !empty($r1['error'])) || (!$r2 || !empty($r2['error'])) || (!$r3 || !empty($r3['error'])) || (!$r4 || !empty($r4['error'])) || (!$r5 || !empty($r5['error']))) {
    echo "\n========================================\n";
    echo "MANUAL STEP REQUIRED:\n";
    echo "Go to your Supabase Dashboard > SQL Editor\n";
    echo "and run the SQL from: database/init/20-notifications-challenges.sql\n";
    echo "and run the SQL from: database/init/30-match-video-analysis.sql\n";
    echo "and run the SQL from: database/init/40-match-jersey-slots.sql\n";
    echo "========================================\n";
}

echo "\nDone.\n";
